- name: copy service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: To install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: To load schema
  ansible.builtin.shell: mysql -h {{ mysql_ip }}  -uroot -p{{mysql_root_password}} < /app/schema/backend.sql

- name: restarting backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    daemon-reload: yes
    enabled: yes


