

- name: copy expense-conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
  register: copy_changed

- name: start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: yes
  when: copy_changed is changed
