- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy expense-conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
  when: copy-changed

- name: start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: yes
  when: copy-changed is changed
