- name: set up prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}
- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: Set root user password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ mysql_root_ip }}